services:
    postgres:
        image: postgres:16
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456789
            - POSTGRES_DB=fastapi

        volumes:
            - postgres-db:/var/lib/postgresql/data
    api:
        build: .
        ports:
            - 8000:8000
        depends_on:
            - postgres
        volumes:
            - ./:/usr/src/app:ro
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        # env_file:
        #     - ./.env
        environment:
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_USERNAME=postgres
            - DATABASE_PASSWORD=123456789
            - DATABASE_NAME=fastapi
            - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=300

volumes:
    postgres-db:
